# https://taskfile.dev

version: "3"

tasks:
  iris:
    aliases:
      - default
      - build
    cmd: qmk compile ./keebio_iris_ce_rev1_funkyoku.json
    silent: true

  iris-default-keymap:
    cmd: qmk compile -kb keebio/iris_ce/rev1 -km default
